AppBundle\Entity\Orders:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\OrdersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        orderId:
            type: integer
            unique: true
            column: order_id
        productId:
            type: integer
            column: product_id
        name:
            type: string
            length: 255
        price:
            type: integer
    lifecycleCallbacks: {  }
